# Requirement 2:
# This is Assignment 11-Casey Quinn


# Requirement 3:

# Commonalities:
* Both Pandas series objects and NumPy arrays are often much more efficient than built-in Python objects such as lists or dictionaries. This is because they both have type-specific compiled code. Both Pandas series objects and NumPy arrays support array-style operations such as slicing.
* Both support uFunc type operations where you can do element-wise operations. This means they have similar capabilities that are lacking with a regular Python list.
# Differences:
* A major difference between them is the index because with a NumPy array it has a fixed integer index with a step of 1 while a Pandas series object can have an explicitly defined index associated with the values. This means that the index values can be of any type. For example, the index in a series could be a string similar to a Python dictionary.
* This gives the series additional capabilities.

# Requirement 4:
<!-- 4. Create a Pandas series named bill_names with American currency bill
denominations as indices (keys) and President last names as values. For
example: 1 – Washington, 2 – Jefferson, etc. -->

In [3]:
import pandas as pd
bill_names = pd.Series({1: 'George Washington', 2: 'Thomas Jefferson',
                        5: 'Abraham Lincoln', 10: 'Alexander Hamilton',
                        20: 'Andrew Jackson', 50: 'Ulysses S. Grant',
                        100: 'Benjamin Franklin', 500: 'McKinley',
                        1000: 'Cleveland', 5000: 'James Madison',
                        10000: 'Salmon P. Chase', 100000: 'Woodrow Wilson'})
bill_names

1          George Washington
2           Thomas Jefferson
5            Abraham Lincoln
10        Alexander Hamilton
20            Andrew Jackson
50          Ulysses S. Grant
100        Benjamin Franklin
500                 McKinley
1000               Cleveland
5000           James Madison
10000        Salmon P. Chase
100000        Woodrow Wilson
dtype: object

# Requirement 5:
<!-- 5. Create a Pandas series-as-dictionary beverages_dict. Make the indices
beverage names and comments about the beverage as values. For example:
‘Aquafina’: ‘This is my favorite bottled water!’. Demonstrate accessing:
• individual values via the keys
• multiple values via slicing -->

In [13]:
beverages_dict = {'Mountain Dew': 'This is my favorite pop but it has a lot of sugar.',
                  'Gatorade': 'This is my favorite beverage when playing soccer!',
                  'Water': 'There is no life without water...',
                  'Whiskey': "Don't drink too much! You may get sick.",
                  'Stoli Doli': 'This is a popular pineapple infused stoli martini at the restaurant I work at.',
                  'Coffee': 'I prefer making French presses when drinking coffee. Try not to drink after 1pm.'}
beverages_dict = pd.Series(beverages_dict)
print('Demonstrations:\n')
print('Accessing individual values via the keys:')
print('Mountain Dew:', beverages_dict['Mountain Dew'])
print('\nDemonstrating accessing multiple values via slicing:')
print('Slice last three rows of the series:\n', beverages_dict[-3:])

Demonstrations:

Accessing individual values via the keys:
Mountain Dew: This is my favorite pop but it has a lot of sugar.

Demonstrating accessing multiple values via slicing:
Slice last three rows of the series:
 Whiskey                 Don't drink too much! You may get sick.
Stoli Doli    This is a popular pineapple infused stoli mart...
Coffee        I prefer making French presses when drinking c...
dtype: object


# Requirement 6:

In [18]:
# obtain real city proper population data
city_pop_dict = {'Chongquing': 31.02e6, 'Shanghai': 27795702, 'Tokyo': 13.96e6, 
                 'Moscow': 12593252, 'Mexico City': 21918936, 'London': 9425622,
                 'New York': 18823000}
population = pd.Series(city_pop_dict)
population.head(10)

Chongquing     31020000.0
Shanghai       27795702.0
Tokyo          13960000.0
Moscow         12593252.0
Mexico City    21918936.0
London          9425622.0
New York       18823000.0
dtype: float64

# Requirement 7:

In [20]:
# -Create a Pandas series-as-dict named city_country with the cities in population and the countries 
# for each city
city_country_dict = {'Chongquing': 'China',
                     'Shanghai': 'China', 
                     'Tokyo': 'Japan',
                     'Moscow': 'Russia',
                     'Mexico City': 'Mexico',
                     'London': 'England',
                     'New York': 'United States'}
city_country = pd.Series(city_country_dict)
city_country

Chongquing             China
Shanghai               China
Tokyo                  Japan
Moscow                Russia
Mexico City           Mexico
London               England
New York       United States
dtype: object

# Requirement 8:

In [28]:
# create a Pandas df object named city_dataframe from a dict of series objects using population 
# and city_country
city_dataframe = pd.DataFrame({'population': population,
                               'city_country': city_country})
print('DataFrame:\n', city_dataframe, '\n')
# this was super cool ;) -> for end comments talk about this
print(f'Showing .index property:\n{city_dataframe.index}\n')
print(f'Showing .columns property:\n{city_dataframe.columns}\n')
print(f'Showing .keys() property:\n{city_dataframe.keys()}\n')


DataFrame:
              population   city_country
Chongquing   31020000.0          China
Shanghai     27795702.0          China
Tokyo        13960000.0          Japan
Moscow       12593252.0         Russia
Mexico City  21918936.0         Mexico
London        9425622.0        England
New York     18823000.0  United States 

Showing .index property:
Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')

Showing .columns property:
Index(['population', 'city_country'], dtype='object')

Showing .keys() property:
Index(['population', 'city_country'], dtype='object')



# Requirement 9:

In [45]:
# create a pandas series object named my_pd_series from coll of string keys and collection of numeric values 
# of your choosing
import numpy as np
grades = np.random.randint(75, 100, size=10)
ind = pd.Index(['Art', 'Music', 'C++', 'Java', 'Multivariable Calculus', 'Mathematical Statistics',
               'Engineering 102', 'Engineering 216', 'Stats 211', 'Cooking Elective'])
my_pd_series = pd.Series(grades, index=ind)

print('Series:\n\n', my_pd_series, sep='')
print('\nModifying Art grade value based on a key:\n')
my_pd_series['Art'] = 94
print(my_pd_series)
print('\nSlicing by explicit index (C++ -> Stats 211)\n')
print(my_pd_series['C++':'Stats 211'])
print('\nSlicing by implicit integer index (the last three):\n')
print(my_pd_series[-3:])
print('\nDemonstrating masking (filtering all grades higher than 85%):\n')
print(my_pd_series[my_pd_series > 85])
print('\nDemonstration of fancy indexing (access grades for C++ and Java):\n')
print(my_pd_series[['C++', 'Java']])
print('\nUsing .loc to access first three grades:\n')
print(my_pd_series.loc['Art': 'C++'])
print('Using .iloc to do the same thing:\n')
print(my_pd_series.iloc[:3])

Series:

Art                        96
Music                      85
C++                        90
Java                       85
Multivariable Calculus     78
Mathematical Statistics    90
Engineering 102            94
Engineering 216            87
Stats 211                  84
Cooking Elective           85
dtype: int64

Modifying Art grade value based on a key:

Art                        94
Music                      85
C++                        90
Java                       85
Multivariable Calculus     78
Mathematical Statistics    90
Engineering 102            94
Engineering 216            87
Stats 211                  84
Cooking Elective           85
dtype: int64

Slicing by explicit index (C++ -> Stats 211)

C++                        90
Java                       85
Multivariable Calculus     78
Mathematical Statistics    90
Engineering 102            94
Engineering 216            87
Stats 211                  84
dtype: int64

Slicing by implicit integer index (the last three)

# Requirement 10: 

In [58]:
# using city_dataframe, demonstrate accessing column via dict style indexing of the column name
# access column via the column names that are strings

# dict style indexing of col name
print('Accessing the population column via dict style method:\n\n', city_dataframe['population'], sep='')
# access via column string
print('\nDoing the same thing but using the other method:\n\n', city_dataframe.population, sep='')

# add a new column to the dataframe named altitude
altitudes = [801, 13.12, 131, 157, 7382, 36, 33]
city_dataframe['altitude'] = altitudes
print(f'\nDataframe with altitude column added:\n\n{city_dataframe}')

Accessing the population column via dict style method:

Chongquing     31020000.0
Shanghai       27795702.0
Tokyo          13960000.0
Moscow         12593252.0
Mexico City    21918936.0
London          9425622.0
New York       18823000.0
Name: population, dtype: float64

Doing the same thing but using the other method:

Chongquing     31020000.0
Shanghai       27795702.0
Tokyo          13960000.0
Moscow         12593252.0
Mexico City    21918936.0
London          9425622.0
New York       18823000.0
Name: population, dtype: float64

Dataframe with altitude column added:

             population   city_country  altitude
Chongquing   31020000.0          China    801.00
Shanghai     27795702.0          China     13.12
Tokyo        13960000.0          Japan    131.00
Moscow       12593252.0         Russia    157.00
Mexico City  21918936.0         Mexico   7382.00
London        9425622.0        England     36.00
New York     18823000.0  United States     33.00


# Requirement 11:

In [77]:
# Create two pandas series that when added using the + create some NaN vals and then use the .add()
# and a fill value to replace the NaN entries
uno = pd.Series(np.random.randint(0, 50, size=10))
doce = pd.Series(np.random.randint(0, 50, size=15))
print(f'Adding two series and producing NaN vals:\n{uno+doce}')
print(f'\n\nUsing .add() method and filling those NaN vals with the mean:\n{uno.add(doce, fill_value=doce.mean())}')

Adding two series and producing NaN vals:
0     58.0
1     72.0
2     46.0
3     61.0
4     44.0
5     29.0
6     67.0
7     50.0
8     37.0
9     48.0
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
dtype: float64


Using .add() method and filling those NaN vals with the mean:
0     58.0
1     72.0
2     46.0
3     61.0
4     44.0
5     29.0
6     67.0
7     50.0
8     37.0
9     48.0
10    52.2
11    72.2
12    70.2
13    32.2
14    56.2
dtype: float64


# Requirement 12:

In [86]:
A = pd.DataFrame(np.random.randint(90, size=(3, 3)),
                columns=list('ABC'))
print('DF #1:\n', A, sep='')
B = pd.DataFrame(np.random.randint(34, size=(4, 4)),
                columns=list('DCBA'))
print('\nDF #2:\n', B, sep='')
print(f'\nAdding and producing NaN values:\n{A+B}')
print(f'\nAdding and filling NaN values:\n{A.add(B, fill_value=B.stack().mean())}')


DF #1:
    A   B   C
0   3  19  84
1  10  22  59
2  36   5  36

DF #2:
    D   C   B   A
0   1  10  19  31
1  25  25  20  27
2  33  11  31  16
3  14  17  29  21

Adding and producing NaN values:
      A     B     C   D
0  34.0  38.0  94.0 NaN
1  37.0  42.0  84.0 NaN
2  52.0  36.0  47.0 NaN
3   NaN   NaN   NaN NaN

Adding and filling NaN values:
        A       B       C       D
0  34.000  38.000  94.000  21.625
1  37.000  42.000  84.000  45.625
2  52.000  36.000  47.000  53.625
3  41.625  49.625  37.625  34.625


# Requirement 13:

In [93]:
rng = np.random.RandomState(42)
A = rng.randint(5, 10, size=(4, 4))
print(f'Array:\n{A}')
print(f'Subtracting row zero from A:\n{A-A[0]}')

Array:
[[8 9 7 9]
 [9 6 7 7]
 [7 9 8 7]
 [9 6 8 6]]
Subtracting row zero from A:
[[ 0  0  0  0]
 [ 1 -3  0 -2]
 [-1  0  1 -2]
 [ 1 -3  1 -3]]


# Requirement 14:

In [99]:
df = pd.DataFrame(A, columns=list('QRST'))
print(f'DataFrame:\n{df}')
print(f'Subtracting row 1 of df using df.iloc[1]:\n{df-df.iloc[1]}')

DataFrame:
   Q  R  S  T
0  8  9  7  9
1  9  6  7  7
2  7  9  8  7
3  9  6  8  6
Subtracting row 1 of df using df.iloc[1]:
   Q  R  S  T
0 -1  3  0  2
1  0  0  0  0
2 -2  3  1  0
3  0  0  1 -1


# Requirement 15:
- None is one of the sentinel values used by Pandas and is a Python singleton object used for missing data in Python coede. None can only be used in arrays with dtype=object. There is typically more overhead and computations are slower with the operations done on the Python level so Pandas also uses NaN as a type for missing values. NaN stands for not a number and is a floating-point value recognized by all systems using IEEE floating-point representation. Arrays with NaN as the missing values can perform computations much faster as we will see in the next requirement. A big difference is that performing aggregations on an array with type None generally results in an error while those operations are well defined with NaN, although the results aren't necessarily meaningful if you do a computations and end up with a NaN value.  

# Requirement 16:

In [116]:
# dem %timeit diff using Python object and Python integers 
array = np.random.randint(0, 1e6, size=1000000)
array2 = np.arange(1e6, dtype='object')
print('Timing sum() aggregation for type int:')
%timeit array.sum()
print(f'\nTiming sum() aggregation for type object:')
%timeit array2.sum()

Timing sum() aggregation for type int:
509 µs ± 8.77 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

Timing sum() aggregation for type object:
26.4 ms ± 404 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Requirement 17: 

In [122]:
data = pd.Series([23, 'Casey Quinn', np.nan, None, 98.7, 
                  'Los Angeles Lakers', [1, 2, 3, 4, 5], None])
print(f'The data is:\n{data}')
# filter out null vals
filt = data.isnull()
print('\nThe null elements are:\n', data[filt], sep='')

The data is:
0                    23
1           Casey Quinn
2                   NaN
3                  None
4                  98.7
5    Los Angeles Lakers
6       [1, 2, 3, 4, 5]
7                  None
dtype: object

The null elements are:
2     NaN
3    None
7    None
dtype: object


# Requirement 18:

In [123]:
df = pd.DataFrame([['np.nan', 78, 89, 78],
                   [90, 89, np.nan, 'Hello'],
                   [-1e6, np.nan, None, 8]], columns=list('QRST'))
print(f'Pandas DataFrame:\n{df}')
print(f'\nDropping all rows containing a null value:\n{df.dropna()}')
print(f'\nDropping all columns containing a null value:\n{df.dropna(axis=1)}\n')
df[4] = np.nan
print('Adding a nan column:\n', df, sep='')
print(f"\nRemoving column with all NaN vals:\n{df.dropna(how='all', axis='columns')}")
print('\nAdding NaN row on the bottem:')
df.loc[3] = np.nan
print(df)
print(f"\nDropping the rows with all NaN values:\n{df.dropna(how='all', axis='rows')}")
print(f"\nFilling all NaN values with 0:\n{df.fillna(0)}")
print(f"\nForward filling all NaN values:\n{df.fillna(method='ffill', axis=1)}")
print(f"\nBack filling all NaN values:\n{df.fillna(method='bfill', axis=1)}")

Pandas DataFrame:
           Q     R     S      T
0     np.nan  78.0  89.0     78
1         90  89.0   NaN  Hello
2 -1000000.0   NaN   NaN      8

Dropping all rows containing a null value:
        Q     R     S   T
0  np.nan  78.0  89.0  78

Dropping all columns containing a null value:
           Q      T
0     np.nan     78
1         90  Hello
2 -1000000.0      8

Adding a nan column:
           Q     R     S      T   4
0     np.nan  78.0  89.0     78 NaN
1         90  89.0   NaN  Hello NaN
2 -1000000.0   NaN   NaN      8 NaN

Removing column with all NaN vals:
           Q     R     S      T
0     np.nan  78.0  89.0     78
1         90  89.0   NaN  Hello
2 -1000000.0   NaN   NaN      8

Adding NaN row on the bottem:
           Q     R     S      T   4
0     np.nan  78.0  89.0     78 NaN
1         90  89.0   NaN  Hello NaN
2 -1000000.0   NaN   NaN      8 NaN
3        NaN   NaN   NaN    NaN NaN

Dropping the rows with all NaN values:
           Q     R     S      T   4
0     np.nan  

# Requirement 19:

In [132]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)

index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print('MultiIndexed:\n', pop, sep='')
pop_df = pop.unstack()
print('\n\nUnstacked:\n', pop_df, sep='')
print('\nStacked:\n', pop_df.stack(), sep='')

MultiIndexed:
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


Unstacked:
                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

Stacked:
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


# Requirement 20: 

In [133]:
motorcycle_brands = pd.Series(['Aprilia', 'BMW', 'Ducati',
                               'Harley Davidson', 'Indian', 'KTM','Suzuki'], 
                              index=[1, 2, 3, 4, 5, 6, 7])
car_brands = pd.Series(['Acura', 'Bentley', 'Buick', 'Cadillac',
                        'Chevrolet', 'Cadillac', 'Bentley', 'Audi'],
                       index=[8, 9, 10, 11, 12, 13, 14, 15])
pd.concat([motorcycle_brands, car_brands])

1             Aprilia
2                 BMW
3              Ducati
4     Harley Davidson
5              Indian
6                 KTM
7              Suzuki
8               Acura
9             Bentley
10              Buick
11           Cadillac
12          Chevrolet
13           Cadillac
14            Bentley
15               Audi
dtype: object

# Requirement 21:

In [138]:
motorcycle_brands = pd.DataFrame(motorcycle_brands)
car_brands = pd.DataFrame(car_brands)
motorcycle_brands.append(car_brands)

0
1           Aprilia
2               BMW
3            Ducati
4   Harley Davidson
5            Indian
6               KTM
7            Suzuki
8             Acura
9           Bentley
10            Buick
11         Cadillac
12        Chevrolet
13         Cadillac
14          Bentley
15             Audi

# Requirement 22:

In [166]:
# one to one join 
df1 = pd.DataFrame({'Name': ['Allen Iverson', 'Kobe Bryant', 'Jason Kidd', 'Chris Paul'],
                   'Position': ['Point Guard', 'Shooting Guard', 'Point Guard', 'Point Guard']})
#                     'Team:': ['76ers', 'Lakers', 'Nets', 'Suns']})
                    
df2 = pd.DataFrame({'Name': ['Allen Iverson', 'Kobe Bryant', 'Jason Kidd', 'Chris Paul'],
                             'Team:': ['76ers', 'Lakers', 'Nets', 'Suns']})

#                     'Position': ['Point Guard', 'Shooting Guard', 'Point Guard', 'Point Guard']})

print('df1\n', df1)
print('df2\n', df2)
df3 = pd.merge(df1, df2)
print(f'df1 and df2 merged:\n{df3}')
df4 = pd.DataFrame({'Position': ['Point Guard', 'Shooting Guard', 'Small Forward'],
                    'Trainer': ['Casey Quinn', 'Connor Quinn', 'Sean Quinn']})
print('Many to one:\n', pd.merge(df3, df4), sep ='')
df5 = pd.DataFrame({'Position': ['Point Guard', 'Point Guard', 'Point Guard', 'Shooting Guard', 'Shooting Guard'],
                   'Skills': ['Crossover', 'Passing', 'Defense', 'Dunking', 'Intimidation']})
print('Many-to-Many:\n', pd.merge(df1, df5), sep='')

df1
             Name        Position
0  Allen Iverson     Point Guard
1    Kobe Bryant  Shooting Guard
2     Jason Kidd     Point Guard
3     Chris Paul     Point Guard
df2
             Name   Team:
0  Allen Iverson   76ers
1    Kobe Bryant  Lakers
2     Jason Kidd    Nets
3     Chris Paul    Suns
df1 and df2 merged:
            Name        Position   Team:
0  Allen Iverson     Point Guard   76ers
1    Kobe Bryant  Shooting Guard  Lakers
2     Jason Kidd     Point Guard    Nets
3     Chris Paul     Point Guard    Suns
Many to one:
            Name        Position   Team:       Trainer
0  Allen Iverson     Point Guard   76ers   Casey Quinn
1     Jason Kidd     Point Guard    Nets   Casey Quinn
2     Chris Paul     Point Guard    Suns   Casey Quinn
3    Kobe Bryant  Shooting Guard  Lakers  Connor Quinn
Many-to-Many:
             Name        Position        Skills
0   Allen Iverson     Point Guard     Crossover
1   Allen Iverson     Point Guard       Passing
2   Allen Iverson     Point G

# Requirement 23:

In [165]:
print('Demonstrating merge with on keyword:\n', pd.merge(df1, df2, on='Name'), sep='')
df3 = pd.DataFrame({'Name': ['Allen Iverson', 'Kobe Bryant', 'Jason Kidd', 'Chris Paul'],
                             'Salary:': ['7.7 million', '21.5 million', '4.9 million', '23.7 million']})



Demonstrating merge with on keyword:
            Name        Position   Team:
0  Allen Iverson     Point Guard   76ers
1    Kobe Bryant  Shooting Guard  Lakers
2     Jason Kidd     Point Guard    Nets
3     Chris Paul     Point Guard    Suns


# Requirement 24:
This assignment was a lot of fun for me. I wish I had given myself one more day to work on it because I was really getting to new concepts in Pandas that like you said require a lot of time to think about. I am excited that I am off work tomorrow to study Pandas more and get going on the next weeks material. It would be helpful ot have some video content but I am sure I can find some on YouTube. 